[Settings]

#AMR IP
server_ip = 10.177.117.1
#AMR port
port=8000


#路徑
[PATH]
up_point = 263,1052
recv_down_point = 1033,1030,1027


[R650]
#送料
down_point = 1205
#收料
recv_up_point = 1200


[R770]
down_point = 1063
recv_up_point = 1065

[R370]
down_point = 175
recv_up_point = 1061

[ICX-8100]
down_point = 1039
recv_up_point = 1041

[UX7]
down_point = 1037
recv_up_point = 1067

[4C]
down_point = 991
recv_up_point = 989

[4D-Revlon1-3]
down_point = 987
recv_up_point = 798

[4E-Revlon2-4]
down_point = 805
recv_up_point = 802

[4J]
down_point = 972
recv_up_point = 971

[4K]
down_point = 970
recv_up_point = 969

[4L]
down_point = 1263
recv_up_point = 1260

[4M]
down_point = 1257
recv_up_point = 1254

[4N]
down_point = 1251
recv_up_point = 1248

[4P]
down_point = 1245
recv_up_point = 1242

[4A-LP48-NEW]
down_point = 1751
recv_up_point = 1749

[4B-LP8-NEW]
down_point = 1747
recv_up_point = 1744

[4C-NEW]
down_point = 1723
recv_up_point = 1724

[4D-Revlon1-3-NEW]
down_point = 1725
recv_up_point = 1726

[4E-Revlon2-4-NEW]
down_point = 1727
recv_up_point = 1728
